title: My Awesome Synecdochy
author: Stefano Geremia
email: stefano_geremia@libero.it
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  A social website for aspiring or experienced poets and readers.
  It will give the users the opportunity to publish their writings freely
  and to create simple interactive games from them such as hangman or crosswords.

# social links
twitter_username: (none)
github_username:  Stef-alt-cpu

show_excerpts: true # set to false to remove excerpts on the homepage
